[2025-02-17T10:36:06.039152+00:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"db_user","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dama.connection_key":"default","dbname":"db_name_test","charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"db_user","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dama.connection_key":"default","dbname":"db_name_test","charset":"utf8mb4"}} []
[2025-02-17T10:36:06.041879+00:00] deprecation.INFO: User Deprecated: Relying on a fallback connection used to determine the database platform while connecting to a non-existing database is deprecated. Either use an existing database name in connection parameters or omit the database name if the platform and the server configuration allow that. (Connection.php:459 called by Connection.php:411, https://github.com/doctrine/dbal/pull/5707, package doctrine/dbal) {"exception":"[object] (ErrorException(code: 0): User Deprecated: Relying on a fallback connection used to determine the database platform while connecting to a non-existing database is deprecated. Either use an existing database name in connection parameters or omit the database name if the platform and the server configuration allow that. (Connection.php:459 called by Connection.php:411, https://github.com/doctrine/dbal/pull/5707, package doctrine/dbal) at /Users/brice/Desktop/formation CDA/Symfony/vendor/doctrine/deprecations/src/Deprecation.php:208)"} []
[2025-02-17T10:36:06.041889+00:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"db_user","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dama.connection_key":"default","charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"db_user","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dama.connection_key":"default","charset":"utf8mb4"}} []
[2025-02-17T10:36:06.042378+00:00] console.CRITICAL: Error thrown while running command "--env=test doctrine:fixtures:load". Message: "An exception occurred in the driver: SQLSTATE[HY000] [2002] Connection refused" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 2002): An exception occurred in the driver: SQLSTATE[HY000] [2002] Connection refused at /Users/brice/Desktop/formation CDA/Symfony/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /Users/brice/Desktop/formation CDA/Symfony/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /Users/brice/Desktop/formation CDA/Symfony/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:33)","command":"--env=test doctrine:fixtures:load","message":"An exception occurred in the driver: SQLSTATE[HY000] [2002] Connection refused"} []
[2025-02-17T10:36:06.042802+00:00] console.DEBUG: Command "--env=test doctrine:fixtures:load" exited with code "2002" {"command":"--env=test doctrine:fixtures:load","code":2002} []
[2025-02-17T11:40:29.572516+00:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"db_user","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dama.connection_key":"default","dbname":"db_name_test","charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"db_user","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dama.connection_key":"default","dbname":"db_name_test","charset":"utf8mb4"}} []
[2025-02-17T11:40:29.575602+00:00] deprecation.INFO: User Deprecated: Relying on a fallback connection used to determine the database platform while connecting to a non-existing database is deprecated. Either use an existing database name in connection parameters or omit the database name if the platform and the server configuration allow that. (Connection.php:459 called by Connection.php:411, https://github.com/doctrine/dbal/pull/5707, package doctrine/dbal) {"exception":"[object] (ErrorException(code: 0): User Deprecated: Relying on a fallback connection used to determine the database platform while connecting to a non-existing database is deprecated. Either use an existing database name in connection parameters or omit the database name if the platform and the server configuration allow that. (Connection.php:459 called by Connection.php:411, https://github.com/doctrine/dbal/pull/5707, package doctrine/dbal) at /Users/brice/Desktop/formation CDA/Symfony/vendor/doctrine/deprecations/src/Deprecation.php:208)"} []
[2025-02-17T11:40:29.575610+00:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"db_user","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dama.connection_key":"default","charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","idle_connection_ttl":600,"host":"127.0.0.1","port":3306,"user":"db_user","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dama.connection_key":"default","charset":"utf8mb4"}} []
[2025-02-17T11:40:29.576149+00:00] console.CRITICAL: Error thrown while running command "--env=test doctrine:schema:create". Message: "An exception occurred in the driver: SQLSTATE[HY000] [2002] Connection refused" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 2002): An exception occurred in the driver: SQLSTATE[HY000] [2002] Connection refused at /Users/brice/Desktop/formation CDA/Symfony/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /Users/brice/Desktop/formation CDA/Symfony/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /Users/brice/Desktop/formation CDA/Symfony/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:33)","command":"--env=test doctrine:schema:create","message":"An exception occurred in the driver: SQLSTATE[HY000] [2002] Connection refused"} []
[2025-02-17T11:40:29.576736+00:00] console.DEBUG: Command "--env=test doctrine:schema:create" exited with code "2002" {"command":"--env=test doctrine:schema:create","code":2002} []
